### ISSUE TITLE
Opening streams

### ISSUE THREAD

**Issue by peterpaulis** [rsms/peertalk#12]
Is there a way to open a NSStream over the connection? This would be much apriechieted

**Comment by rsms** [comment]
You can use PTUSBHub connectToDevice... and use the dispatch_io_t, which you can probably wrap with a NSStream. AFAIK NSStream is built on top of libdispatch and io channels.

**Comment by peterpaulis** [comment]
not sure about that, looks like NSStream implements even a lower api than dispatch_io...

**Comment by peterpaulis** [comment]
ok, did manage to trick it wit this
https://github.com/peterpaulis/BufferOutputStreamToInputStream

i 'simulate' an NSStream
