### ISSUE TITLE
Connect more than one ios device to OSX

### ISSUE THREAD

**Issue by artem-exd** [rsms/peertalk#31]
Hi,
great work. 
Is there way to connect two ios devices to OSX and recognize where is first and where is second, I need to make app bundle source synchronization between two ios devices through USB connected to OSX. 
I need to sync, video and images not loaded in memory, as a files.
is there possible?
thank you very much.

**Comment by daniel-bluesea** [comment]
@artem-sherbachuk did you mange to do it?
