### ISSUE TITLE
visit website provided by http-server

### ISSUE THREAD

**Issue by menglexiang** [rsms/peertalk#46]
I setup a http-server on Macbook, then perform  "iproxy 8080 8080", finally I need to visit the website on an iPhone, can I directly enter 127.0.0.1:8080 safari it? or write an APP, which wrapped peertalk.

best wish for you ,i am not good at english.:-D

**Comment by XAS-712** [comment]
Maybe Safari can't use a connection from other applications.
I tried to make a SSH channel and access the server in a private network, but it doesn't work.
