### ISSUE TITLE
Tag  master with a new version

### ISSUE THREAD

**Issue by pkrmf** [rsms/peertalk#48]
When pulling PeerTalk through CocoaPods it is not pulling the latest codebase. Its actually pulling an old commit since version 0.0.1 points to an old commit.

Would it be possible to push a new podspec to cocoapods master repo for version 0.0.2 and tag the master branch with tag 0.0.2?

I can do a PR for the podspec if you will

**Comment by priteshrnandgaonkar** [comment]
Any updates on this?

**Comment by pkrmf** [comment]
@priteshrnandgaonkar doesn’t seem there is much we can do here... any ideas?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonathandann** [comment]
You can pull the latest version directly from GitHub using 

`pod 'PeerTalk', :git => 'https://github.com/rsms/PeerTalk', :tag => '0.1.0'`

This was pushed today.
