### ISSUE TITLE
PTUSBHub failed to initialize: Error

### ISSUE THREAD

**Issue by godwinjoseph-wisilica** [rsms/peertalk#52]
I can't initialize PTUsbHub

PTUSBHub failed to initialize: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"

**Comment by GintokiS** [comment]
Yes, I got this problem too. My stuff is MacOS 10.14.4, Xcode 11.1. Deployment target is 10.14.
After set breakpoint, I found the init fail at PTUSBHub.m L:354 `if (connect(fd, (struct sockaddr*)&addr, socklen) == -1) `

But, if I copy -openOnQueue:error:onEnd to a new command line tool project, socket will open success.

So, someone can help me?

**Comment by godwinjk** [comment]
I have solved it by setting Mac Os sand box settings

**Comment by GintokiS** [comment]
When I close Sandbox my app run well.

@godwinjk  Thanks!

**Comment by jonathandann** [comment]
The README now contains information about running under the macOS Sandbox
