### ISSUE TITLE
Error while testing Simulator and mac app

### ISSUE THREAD

**Issue by irshadpc** [rsms/peertalk#9]
I got error when i was running both app and my display was stuck with some time and the both app did got error after my display blinking.After that the sample project crash with the below method
- (void)readAndDiscardDataOfSize:(size_t)size overChannel:(dispatch_io_t)channel callback:(void(^)(NSError*, BOOL))callback .

Actually what you did with my systems.

**Comment by ichu501** [comment]
Yes,when I was testing my iPhone 5s it seems to be the same scenarios

**Comment by rsms** [comment]
To reproduce with different hardware would be to do this:

- Have two different Macs and two different iOS devices
- Connect Mac A with iOS device A and get the same results
- Connect Mac B with iOS device B and get the same results
- Connect Mac B with iOS device A and get the same results

I'm assuming you found `readAndDiscardDataOfSize` to be at the top of the call stack on your *Mac* when thing crash for you. If this is on the *iOS device* then your reproduction on two different devices might be enough to prompt a lengthy debugging session.

**Comment by ichu501** [comment]
Yah sure i will do this ,i need some time to do this.

On Mon, Jan 5, 2015 at 8:41 AM, Rasmus <notifications@github.com> wrote:

> To reproduce with different hardware would be to do this:
>
>    - Have two different Macs and two different iOS devices
>    - Connect Mac A with iOS device A and get the same results
>    - Connect Mac B with iOS device B and get the same results
>    - Connect Mac B with iOS device A and get the same results
>
> I'm assuming you found readAndDiscardDataOfSize to be at the top of the
> call stack on your *Mac* when thing crash for you. If this is on the *iOS
> device* then your reproduction on two different devices might be enough
> to prompt a lengthy debugging session.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsms/peertalk/issues/9#issuecomment-68663782>.
>



-- 
Thanks&
Regards.........


Irshad pc
09947187988
ichu501@gmail.com

**Comment by liyangv** [comment]
I met the same error while Duet is running in the background, turn off/uninstall Duet. problem solved,
